version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/" # Root directory where the Dockerfile is located
    schedule:
      interval: "weekly" # Check for updates daily
    ignore:
      - dependency-name: "ghcr.io/astral-sh/uv" # Optional: Ignore specific versions if needed
    labels:
      - "dependencies"
      - "docker"
