# GitHub Actions workflow to run tests on pull requests.

name: run-tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Install dependencies
        run: |
          uv sync --frozen --no-install-project
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              wget \
              libatk-bridge2.0-0 \
              libatk1.0-0 \
              libgbm1 \
              libgtk-3-0 \
              libnspr4 \
              libnss3 \
              ca-certificates \
              fonts-liberation \
              libasound2t64  \
              libx11-xcb1 \
              libxcomposite1 \
              libxcursor1 \
              libxdamage1 \
              libxi6 \
              libxrandr2 \
              libxss1 \
              libxtst6 \
              x11-utils \
              curl \
              jq \
              unzip && \
          CHROME_VERSION=$(wget -qO- "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" | \
          python -c "import sys, json; v=json.load(sys.stdin); print(v['channels']['Stable']['version'])") && \
          wget "https://storage.googleapis.com/chrome-for-testing-public/${CHROME_VERSION}/linux64/chrome-linux64.zip" && \
          unzip chrome-linux64.zip && \
          mv chrome-linux64 /opt/ && \
          sudo rm -f /usr/bin/google-chrome && \
          sudo ln -s /opt/chrome-linux64/chrome /usr/bin/google-chrome && \
          rm -rf chrome-linux64 chrome-linux64.zip
          google-chrome --version
      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $5}') && \
          echo "Installed Chrome version: $CHROME_VERSION" && \
          CHROMEDRIVER_VERSION=$(wget -qO- "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" | \
          python -c "import sys, json; v=json.load(sys.stdin); print(v['channels']['Stable']['version'])") && \
          wget "https://storage.googleapis.com/chrome-for-testing-public/${CHROMEDRIVER_VERSION}/linux64/chromedriver-linux64.zip" && \
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver
          chromedriver --version

      - name: pytest
        run: |
          source .venv/bin/activate
          HEADLESS=True \
          pytest tests/ -v -n auto --cov=. --cov-report= --cov-fail-under=80
